import type { ProofBenchArtifact } from '@/lib/benchmarkops';
import type { PlatformArtifact, PlatformBenchmarkRun, PlatformProjectBundle, PlatformProblemItem } from '@/lib/platform-types';

export const benchmarkOpsAdminViews = ['projects', 'items', 'sources'] as const;

export type BenchmarkOpsAdminView = (typeof benchmarkOpsAdminViews)[number];

export type BenchmarkOpsAdminTab = {
  key: BenchmarkOpsAdminView;
  label: string;
};

export type BenchmarkOpsSectionIntro = {
  eyebrow: string;
  title: string;
  body: string;
  align?: 'start' | 'compact';
};

export type BenchmarkOpsViewIds = {
  adminTabs: string;
  projectName: string;
  projectDescription: string;
  sourceUpload: string;
  itemTitle: string;
  itemPrompt: string;
  itemAnswer: string;
  itemSubject: string;
  itemGradeLevel: string;
  itemDifficulty: string;
  itemType: string;
  itemTags: string;
  itemNotes: string;
  runMode: string;
  runModelName: string;
  runBaseUrl: string;
  runRuns: string;
  runParallelism: string;
  runTemperature: string;
  runMaxTokens: string;
};

export type BenchmarkOpsRunConfig = {
  mode: 'sync' | 'async';
  baseUrl: string;
  modelName: string;
  runs: number;
  parallelism: number;
  temperature: number;
  maxTokens: number;
};

export type BenchmarkOpsItemDraft = {
  title: string;
  prompt: string;
  answerKey: string;
  subject: string;
  gradeLevel: string;
  difficulty: string;
  itemType: string;
  tags: string;
  notes: string;
};

export type BenchmarkOpsViewModel = {
  bundles: PlatformProjectBundle[];
  selectedProjectId: string;
  selectedItemId: string;
  adminView: BenchmarkOpsAdminView;
  runConfig: BenchmarkOpsRunConfig;
  itemForm: BenchmarkOpsItemDraft;
  projectName: string;
  projectDescription: string;
  selectedBundle: PlatformProjectBundle | null;
  selectedItem: PlatformProblemItem | null;
  recentRuns: PlatformBenchmarkRun[];
  latestRun: PlatformBenchmarkRun | null;
  artifactMap: Map<string, PlatformArtifact[]>;
  liveArtifact: ProofBenchArtifact | null;
  liveRunId: string | null;
  banner: string | null;
  error: string | null;
  busyKey: string | null;
  lastUpdatedText: string;
};

export type BenchmarkOpsConsoleCopy = {
  heroEyebrow: string;
  heroTitle: string;
  heroBody: string;
  heroPrimary: string;
  heroSecondary: string;
  summaryCards: Array<{ label: string; hint: string }>;
  workspaceTitle: string;
  workspaceHeadline: string;
  workspaceBody: string;
  projectName: string;
  projectDescription: string;
  createProject: string;
  intakeTitle: string;
  intakeHeadline: string;
  intakeBody: string;
  uploadSource: string;
  uploadFolder: string;
  uploadHint: string;
  problemTitle: string;
  problemHeadline: string;
  problemBody: string;
  createItem: string;
  runTitle: string;
  runHeadline: string;
  runBody: string;
  resultsTitle: string;
  resultsHeadline: string;
  resultsBody: string;
  previewTitle: string;
  previewHeadline: string;
  previewBody: string;
  governanceTitle: string;
  governanceHeadline: string;
  governanceBody: string;
  emptyProjects: string;
  emptyItems: string;
  emptyRuns: string;
  emptyPreview: string;
  selectedItem: string;
  selectedProject: string;
  syncMode: string;
  asyncMode: string;
  startRun: string;
  refresh: string;
  preview: string;
  download: string;
  running: string;
  queued: string;
  completed: string;
  failed: string;
  draftItemTitle: string;
  draftItemPrompt: string;
  draftItemAnswer: string;
  subject: string;
  gradeLevel: string;
  difficulty: string;
  itemType: string;
  tags: string;
  notes: string;
  members: string;
  permissions: string;
  sourceFiles: string;
  runMode: string;
  baseUrl: string;
  modelName: string;
  runs: string;
  parallelism: string;
  temperature: string;
  maxTokens: string;
  lastUpdate: string;
  accuracy: string;
  artifacts: string;
  diagnostics: string;
  manualItemHint: string;
  supportedFiles: string;
  enterpriseNotice: string;
  genericExport: string;
  countSuffix: string;
  uploadFieldLabel: string;
  projectCountLabel: string;
  itemCountLabel: string;
  runCountLabel: string;
  artifactCountLabel: string;
  importedCountLabel: string;
  sourcePathLabel: string;
  sourceArtifactsLabel: string;
  sourceOriginalLabel: string;
  sourceNormalizedLabel: string;
  sourceTextLabel: string;
  sourceLatexLabel: string;
  runIdentifierLabel: string;
  answerValidationTitle: string;
  latencyLabel: string;
};
